build: Prefer Python from environment
9be1af2b1a4b4040c823206099de6705363b1349 switched to modern `python` module, which will use Meson’s Python instance by default.
See https://mesonbuild.com/Python-module.html#find_installation

> That argument is optional, if not provided then the returned python installation will be the one used to run Meson.

That fails in Nixpkgs, where Meson is shrinkwrapped with a minimal Python interpreter without any modules:

    ERROR: Problem encountered: PyGObject is required.

Instead, we should use `python3` special value, which makes Meson search the environment.
The argument-less version is a mistake IMO: https://www.github.com/mesonbuild/meson/issues/7415