gitlab-ci: move to debian testing image as base.
It looks like Arch does not have mingw64 cross-compilers in core package
repository. It does have some package in the user repository (AUR), but
I assume that such a repository cannot be deemed as safe.

Anyway I still tried, but apparently these AUR packages have to be built
and when I tried, I got this error:
>  ERROR: Running makepkg as root is not allowed as it can cause
> permanent, catastrophic damage to your system.
(I was not even running anything as root, does it mean that any command
run inside the CI system is run as root by default?)

Anyway it's all a big mess. So this is my attempt to move to Debian
testing, which is anyway our base compatibility system.