build: adding info about new Cornish language.
This was failing our build when -Dwindows-installer=true thanks to
integrity rules. Note that there is no iso-639 gettext module for kw, so
I found the "Kernewek" translation with Wikipedia.
There is no Inno code module that I could find.

Fixes:

> Error: languages listed in iso_639_custom.xml do not match the .po files in po/.
> - Faulting 'dl_code' on iso_639_custom.xml: kw

(cherry picked from commit 0c5117e2102acd418e21a0ebac9f480f3e5a8642)