tools: make file writable on Windows to make it deletable.
Python's os.chmod() docs say:

> Although Windows supports chmod(), you can only set the file’s
> read-only flag with it (via the stat.S_IWRITE and stat.S_IREAD
> constants or a corresponding integer value). All other bits are
> ignored.

This added flag would hopefully fix the following error on the Windows
CI jobs:

> INFO: Running: shutil.rmtree(C:\Gitlab\builds\FEC5kCEFp\0\GNOME\gimp\_build-clangarm64\.GIMP3-build-config-cxyx9y)
> Error: [WinError 5] Access is denied: 'C:\\Gitlab\\builds\\FEC5kCEFp\\0\\GNOME\\gimp\\_build-clangarm64\\.GIMP3-build-config-cxyx9y\\plug-ins\\file-ico\\file-ico.exe'

(cherry picked from commit 51f52af6aab13e331bd071a2c9ba4c2cd90744b0)