build/linux: Fix bashisms
Fix 2 bashisms:

    error: build/linux/appimage/3_dist-gimp-goappimage.sh: Unterminated
    quoted string found, EOF reached. Wanted: <">, opened in line 49

    error: build/linux/appimage/3_dist-gimp-goappimage.sh: Unterminated
    quoted string found, EOF reached. Wanted: <">, opened in line 473

via factor out AppImage detection to it's own variable and using cat >
.. << EOF form.

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>
(cherry picked from commit 43572ef591866da9955719fda419f89925ea2adb)